name: Distributed Banking CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install User Service Dependencies
      run: |
        cd user-service
        pip install -r requirements.txt

    - name: Install Payment Service Dependencies
      run: |
        cd payment-service
        pip install -r requirements.txt

    - name: Install Transaction Service Dependencies
      run: |
        pip install flask

    - name: Check Python Files
      run: |
        python -m py_compile user-service/app.py
        python -m py_compile payment-service/app.py
        python -m py_compile transaction-service/app.py